
- include: prelim.yml
- include: patch_udev.yml

- name: Check of the identifier for tplink725 is present
  shell: "lsusb | grep 0bda:8179 | wc |gawk '{print $1}'"
  register: usb_response
  ignore_errors: true

- name: Use compiled hostapd, and wpa_supplicant if tplink WM725M
  set_fact:
     wifi_id: tplink_WM725M
  when:  usb_response.stdout|int > 0

- include: hw_rpi2.yml
  when: rpi_model is defined and rpi_model == "rpi2"

- name: Check if the identifier for intel's NUC6 builtin wifi is present
  shell: "lsusb | grep 8087:0a2b | wc |gawk '{print $1}'"
  register: usb_NUC6
  ignore_errors: true

- name: download the firmware for built in wifi on NUC6
  get_url: dest=/lib/firmware
           url={{ xsce_download_url }}/iwlwifi-8000C-13.ucode
  when:  usb_NUC6.stdout|int > 0

# need to add proper download section and get the binary out of git
- name: copy  the firmware for tplink WM752M
  copy: src=rtl8188eufw.bin dest=/lib/firmware/rtlwifi/
  when: wifi_id  ==  "tplink_WM725M" and xo_model == "none" and not rpi_model is defined
  ignore_errors: true
