- name: get the required build packages 
  package: name={{ item }}
           state=present
  with_items:
    - build-essential 
    - gettext
    - python-dev
    - libicu-dev 
    - libxslt1-dev 
    - libfreetype6-dev 
    - libjpeg-dev 
    - enscript
    - python-virtualenv 
    - ttf-liberation
  when: schooltool_install
  tags:
    - download
  
- name: get the ttf-ubuntu-font-family
  get_url: url={{ xsce_download_url }}/ubuntu-font-family-0.83.zip
           dest={{ downloads_dir }}
  tags: download2

- name: expand the ttf fonts to the right place
  unarchive: src={{ download_dir }}/ubuntu-font-family-0.83.zip
             dest=/usr/share/fonts/truetype/ttf-ubuntu/

- name: get the schooltool source
  get_url: src={{ xsce_download_url }}/{{ schooltool_src }}
           dest={{ downloads_dir }}
  tags: download2

- name: expand source to dest
  unarchive: src={{ downloads_dir }}/{{ schooltool_src }}
             dest= {{ xsce_dir }}

- name: build the schooltool from source
  shell: command='cd {{ xsce_dir }}/2.8; make '

