- name: Disable firewalld service
  service: name=firewalld
           enabled=no

- name: Use larger hammer to disable firewalld (2 symbolic links involved)
  shell: "systemctl disable firewalld.service"

- name: Mask firewalld service
  shell: 'systemctl mask firewalld'
  ignore_errors: yes
  when: not installing

- name: Stop firewalld service
  service: name=firewalld
           state=stopped
  ignore_errors: yes
  when: not installing

- name: Remove iptables.service file from /etc
  file: path=/etc/systemd/system/iptables.service 
        state=absent

- name: Remove iptables-xs.service file from /etc
  file: path=/etc/systemd/system/iptables-xs.service 
        state=absent

- name: Install iptables service package
  yum: name=iptables-services
       state=installed
  tags:
    - download

- name: Install connection tracking tools 
  yum: name=conntrack-tools
       state=installed
  tags:
    - download

- name: Install iptables services
  template: src={{ item.0 }}
            dest={{ item.1 }}
            owner='root'
            group='root'
            mode={{ item.2 }}
  with_items:
   - { 0: 'gateway/iptables-config', 1: '/etc/sysconfig/iptables-config', 2: '0644' }
   - { 0: 'gateway/check-LAN', 1: '/usr/bin/check-LAN', 2: '0755' }
   - { 0: 'gateway/apache', 1: '/etc/sudoers.d/apache', 2: '0640' }

- name: Create a flat file for users who have been captured (no redirection)
  file: path=/var/lib/users
        state=touch
        owner=root
        group=apache
        mode=0660
# format of this file: ip <space> MAC <space> `date +%s`


