- name: Get the kiwix software
  get_url: url="{{ xsce_download_url }}/{{ kiwix_src_file }}"  dest="{{ downloads_dir }}/{{ kiwix_src_file }}" timeout=1000
  when: not {{ use_cache }} and not {{ no_network }}
  tags:
    - download2

- include: kiwix_install.yml
  when: kiwix_src_file is defined
  tags:
    - kiwix

- debug:  msg="WARNING kiwix source is not defined for your platform"
  when: not kiwix_src_file

