- name: Base Server Installed
  command: echo Base Server Installed

- name: Restart xsce-cmdsrv service
  service: name=xsce-cmdsrv
           state=restarted
  when: not installing

- name: Restart httpd
  service: name=apache2
           state=restarted
  when: not installing

- name: Create hidden xsce-prepped file
  file: dest=/.xsce_base_ver
        state=touch

# If we got here we're done
- name: Create hidden xsce-base file 
  lineinfile: dest=/.xsce_base_ver
              regexp='^VERSION=*'
              line='VERSION="{{ gui_version }}"'
              state=present
  when: not installing
