- name: Install vnc packages
  package: name={{ item }}
           state=present
  with_items:
        - tigervnc-server
        - python-websockify
#        - mate-desktop-environment-extras
  when: ansible_distribution == "Fedora" or ansible_distribution == "CentOS"
  tags: download

- name: Install vnc packages
  package: name={{ item }}
           state=present
  with_items:
        - vnc4server
        - websockify
  when: ansible_distribution == "Debian"
  tags: download

- name: Download the noVNC source from our copy
  get_url: url={{ xsce_download_url }}/{{ novnc_version }}.tar.gz
           dest={{ downloads_dir }}
  tags: download2

- name: Expand novnc to our root directory
  unarchive: src={{ downloads_dir }}/{{ novnc_version }}.tar.gz
           dest={{ xsce_base }}
           owner=xsce-admin

- name: Create a link pointing to the current version
  file: src={{ xsce_base }}/{{ novnc_version }}
        dest={{ xsce_base }}/novnc
        state=link  

- name: make the vnc directory
  file: path=/home/xsce-admin/.vnc
        owner=xsce-admin
        state=directory

- name: Put templated files in place
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=xsce-admin
            mode=0755
  with_items:
     - { src: 'cmdsrv/xstartup', dest: '/home/xsce-admin/.vnc/' }
     - { src: 'cmdsrv/vnc', dest: '/etc/init.d/' }
     - { src: 'cmdsrv/websockify.service', dest: '/etc/systemd/system/' }

- name: Retrieve the LXDE config files into downloads
  get_url: url={{ xsce_download_url }}/lxde_rpi3_raspbian.tgz
           dest={{ downloads_dir }}
  tags: download2

- name: Put the lxde config files in place
  unarchive: src={{ downloads_dir }}/lxde_rpi3_raspbian.tgz
             dest=/home/xsce-admin/
             owner=xsce-admin

- name: copy the password file -- binary confuses template module
  copy: src=cmdsrv/passwd
        dest=/home/xsce-admin/.vnc
        mode=0700
        owner=xsce-admin 
