- name: Set flag for fedora 18
  set_fact:
    is_F18: True
  when: ansible_distribution_release == "based on Fedora 18" or ansible_distribution_version == "18"

- name: get the uuidgen program
  package: name=uuid-runtime
           state=present
  when: is_debian

# for rpi, without rtc, we need time as soon as possible
- name: Install chrony package
  package: name={{ item }}
           state=present
  with_items:
   - chrony
  tags:
    - download

#TODO: Use regexp filter instead of hard-code ip 
- name: Update chrony config file
  template: backup=no
            dest=/etc/chrony.conf
            src=chrony.conf.j2

- include: selinux.yml
  when: ansible_selinux is defined and ansible_version >= '2' and ansible_selinux or ansible_selinux['status'] is defined and ansible_version < '2' and ansible_selinux['status'] != 'disabled'


- include: computed_vars.yml

- include: detected_network.yml
  when: not installing

- include: patch-udev.yml

- include: prep.yml

# Put conditional actions for hardware platforms here
##  DISCOVER PLATFORMS ######
- name: Discover if this is a rpi2 -- if so it has a bcm2709 processor
  set_fact: 
     rpi_model: "rpi2"
  when:  ansible_cmdline["bcm2709.serial"]  is defined
  ignore_errors: true

- include: raspberry_pi_2.yml
  when: rpi_model != "none"

- name: Check if the identifier for intel's NUC6 builtin wifi is present
  shell: "lsusb | grep 8087:0a2b | wc |gawk '{print $1}'"
  register: usb_NUC6
  ignore_errors: true

- name: download the firmware for built in wifi on NUC6
  get_url: dest=/lib/firmware
           url={{ xsce_download_url }}/iwlwifi-8000C-13.ucode
  when:  usb_NUC6.stdout|int > 0

